name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python model.py

    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: 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
      run: |
        pip install huggingface_hub
        huggingface-cli login --token $HF_TOKEN
        huggingface-cli repo create your-model-repo-name
        git clone https://huggingface.co/spaces/your-model-repo-name
        cp student_score_predictor.pkl your-model-repo-name/
        cd your-model-repo-name
        git add .
        git commit -m "Deploy model"
        git push
